on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
    types: [opened, reopened, synchronize]
  workflow_call:
  workflow_dispatch:

name: ci-build

env:
  DOTNET_VERSION: 8.0.x
  REGISTRY: ghcr.io

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup .NET SDK ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal
      
      - name: Publish Manager Discord Bot
        run: dotnet publish ManagerDiscordBot/ManagerDiscordBot.csproj -c Release -o ./publish/ManagerDiscordBot
      
      - name: Upload Manager Discord Bot artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ManagerDiscordBot
          path: publish/ManagerDiscordBot/*
          retention-days: 1
          if-no-files-found: error
      
  containerize:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github

      - uses: ./.github/actions/containerize
        with:
          registry: ghcr.io
          registry-path: ${{ github.repository_owner }}/manager-discord-bot
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          artifact-name: ManagerDiscordBot
          push-image: ${{ github.ref_type == 'branch' && github.ref_protected && github.event_name != 'pull_request' }}